### ISSUE TITLE
gdImageCreateFromGif() hangs on invalid gif data

### ISSUE THREAD

**Issue by Barro** [libgd/libgd#158]
gdImageCreateFromGif() hangs when making it read invalid gif data on libgd 2.1.1 and the same bug is in the latest git master version (18bbbfa8af13a27003b30286be2671b0e2d50ace). You can try out this with following program:

```c
#include <gd.h>
#include <stdlib.h>

int main(int argc, char* argv[])
{
    gdImagePtr image = NULL;
    image = gdImageCreateFromGif(stdin);
    gdFree(image);

    return EXIT_SUCCESS;
}
```

```bash
$ gcc -static -o libgd-gif-runner libgd-gif-runner.c -lgd -lm
$ ./libgd-gif-runner < /fuzzfiles/gif-hang-id\:000023\,src\:000020+000276\,op\:splice\,rep\:1.gif
```

Unfortunately as this issue tracker does not support file attachments, here is the gif image that causes the hang as base64 encoded fille:

    R0lGODlh4+Pj4+Pj4+Pj4+Pj4+Pj4////wAAAAAALAAAAAAgABgAAAch+QQAAAAAACwAAAAAIAAY
    AAAHF5wKCgoKCgogCvIKCgoAAAAAgCwAAO8Ke6nLjQAM

**Comment by fgeek** [comment]
Any updates on this issue?

**Comment by vapier** [comment]
nope. if a dev was looking at it, we'd usually post or close it.

**Comment by vapier** [comment]
while i'm not super familiar with the LZW compression format (used by this gif), i'm not sure this is a bug.  the file generates a pretty large image and has highly compressed data in it.  while running under ASAN makes it run pretty slow (because of all the memory operations), it doesn't make it hang ... just give it a few minutes to finish.  if you build w/out ASAN, then it runs pretty quickly.

throw the image into gimp and watch it struggle too :).

**Comment by velemas** [comment]
https://bugs.php.net/bug.php?id=75571 may be related. It is fixed in PHP.

**Comment by cmb69** [comment]
> throw the image into gimp and watch it struggle too :).

Then GIMP also would have a bug, since the image does not contain any actual image data (just where these should start, the file is truncated; the last byte `0C` is the LZW Minimum Code Size).

**Comment by velemas** [comment]
@cmb69 then, please, report to GIMP too.
