### ISSUE TITLE
Unit test frameworks?

### ISSUE THREAD

**Issue by lilith** [libgd/libgd#161]
When working on [FastScaling](https://github.com/imazen/resizer/tree/926fe2e615a20d82ece5e50632409591c2dbf45c/Plugins/FastScaling/NativeFastScaling), we found [Catch](https://github.com/philsquared/Catch) and [Theft](https://github.com/silentbicycle/theft) to be extremely useful. 

I hope that libgd can consider C++ for extended unit and scoped fuzz testing, as options are quite poor within the C89 space. 

Running [valgrind against these normal and fuzz tests with travis](https://github.com/imazen/resizer/blob/926fe2e615a20d82ece5e50632409591c2dbf45c/.travis.yml) was invaluable in catching security flaws.

**Comment by pierrejoye** [comment]
How c++ helps here?

**Comment by nathanaeljones** [comment]
Literate tests; detailed parameter expansion - modern test frameworks make debugging trivial. I have not found any C test libraries that come close at all; they are much more wasteful of developer time.

**Comment by pierrejoye** [comment]
It depends.

Also will always support C as primary APIs. Testing it using C++ may make
things more complicated that it should.

The tests are as close as they can from the exposed APIs and ensure unit
testing covering C usages, and real world usages.

I indeed like c++ for some projects but I miss the point here. If you have
arguments or examples to make c++ usage for unit testing a good thing pls
fire them :)

Obviously if someone is interested to take over the c++ APIs, then it makes
sense to use c++ as well to test it.

**Comment by vapier** [comment]
i don't think the point is so much the language choice as using an existing test framework like [googletest](https://github.com/google/googletest).  basically many of the helpers we have in [/tests/gdtest/](https://github.com/libgd/libgd/tree/master/tests/gdtest) would be covered by the framework, and we'd have a standardized test runner rather than every test itself defining `main()`.

i don't think our needs at this point are that complicated, but if someone wanted to volunteer and invest the energy in converting to gtest, i wouldn't say no.

**Comment by pierrejoye** [comment]
I fully agree :)

**Comment by pierrejoye** [comment]
Closing for now. If one has an idea and time to replace our rather basic gdTest, happy to use it :)
