### ISSUE TITLE
Add coverity add-ons to travis

### ISSUE THREAD

**Issue by pierrejoye** [libgd/libgd#219]
https://scan.coverity.com/travis_ci

**Comment by pierrejoye** [comment]
@vapier @cmb69  please request to join libgd/libgd on coverity :)

**Comment by cmb69** [comment]
Done. :)

**Comment by pierrejoye** [comment]
It is added now.

I am not sure about creating one specific branch for that but using current stable sounds reasonable, it should not have too many commits. For master we can upload builds once a week or so. Thoughts?

**Comment by vapier** [comment]
current stable sounds fine.  i haven't played with coverity before though, so i'll need to do so.

**Comment by pierrejoye** [comment]
Pretty good tool. It will keep us busy :)

**Comment by cmb69** [comment]
> Pretty good tool. It will keep us busy :)

ACK, but it seems worth the trouble. :)

> current stable sounds fine.

ACK.

**Comment by cmb69** [comment]
BTW, shouldn't we add a [Coverity Scan Badge](https://scan.coverity.com/projects/libgd?tab=project_settings) to README.md?

**Comment by pierrejoye** [comment]
Later :)

**Comment by pierrejoye** [comment]
Except @cmb69 pull request, all current detected flaws have been sorted out and either with a fix applied or marked as false positive.

**Comment by pierrejoye** [comment]
All issues fixed, status added to the readme. Let close that. Thanks all :)

New future detected issues can be handled in separate issues or there

**Comment by vapier** [comment]
i ended up reworking the code significantly.  turns out when coverity throttles you, its addon exits the build immediately.  that means none of our build scripts/tests were actually running!  it's been this way for the last couple builds in the GD-2.2 branch.

with commit 9421641c2632, i changed it to only run coverity on the first build (linux+gcc), and do so by hand.  there should be little difference in coverage between OS X and clang, and clearly trying to post 4 builds is too much for their rate limits.

**Comment by pierrejoye** [comment]
Thanks! Good catch!

I was wondering why it seemed to have reach the limit sometimes and I was expecting travis to call it only once per commit and not for each build :/

Or maybe coverity should detect the main build id from travis and do not run for something it has tested already or being tested at this moment.
