### ISSUE TITLE
FAIL gdimagerotate/bug00067 (i686)

### ISSUE THREAD

**Issue by remicollet** [libgd/libgd#242]
Reproduced on Fedora and RHEL 6-7, i386 only (ok on RHEL-5 i386, ok on other distro on x86_64))

```
gdimagerotate/bug00067.c:46: Total pixels changed: 14143 with a maximum channel difference of 255.
gdimagerotate/bug00067.c:47: comparing rotated image to ./gdimagerotate/bug00067_150_exp.png failed.
FAIL gdimagerotate/bug00067 (exit status: 1)
```

bug00067.c_46_diff.png
![bug00067 c_46_diff](https://cloud.githubusercontent.com/assets/176950/16347503/13392be6-3a1b-11e6-8175-2d5a296c38fd.png)

bug00067.c_46_out.png
![bug00067 c_46_out](https://cloud.githubusercontent.com/assets/176950/16347507/1670dcd2-3a1b-11e6-9d66-779f4eaad40c.png)

**Comment by remicollet** [comment]
Summary: 
* it passes on armv7h
* it passes on x86_64
* it fails on i686 (RHEL 6-7)
* it passes on i386 (RHEL 5)

**Comment by pierrejoye** [comment]
Looks like rounding issues on x86. Not sure how we can solve this test to work the same way on all architectures. 

Also some pixels seem to have 255 channel delta, but may pdiff will make it.

Alternatively debug the implementation to be sure that the rounding are as good on x86 than other. Quite longer task :)

**Comment by pierrejoye** [comment]
Let see once we have pdiff if it passes.

If that's not the case we need a way to skip/xfail per architecture as I suppose 686 may not be the only processor with different results. Unless one can spot obvious 686 flaws in the current calculation implementations.

**Comment by vapier** [comment]
seems to be due to the default of `-mfpmath=386` with older systems.  if you have a system that isn't ancient, simply adding `-msse -mfpmath=sse` to `CFLAGS` lets the test pass.

imo we should just punt this.

**Comment by pierrejoye** [comment]
Good catch! Go ahead :) One can use CFLAGS environment on configure call

**Comment by vapier** [comment]
you want to try and auto-add `-msse -mfpmath=sse` to `CFLAGS` in `configure.ac` for 32-bit x86 systems ?  i'm generally of the opinion that projects shouldn't mess with compiler settings in an attempt to magically figure out the "right" answer.  if you're building software for your system instead of getting it from your distro (who will take care of this stuff for you), then i think it's your responsibility to deal with this.

**Comment by pierrejoye** [comment]
@RemiCollet thought?

**Comment by remicollet** [comment]
> if you're building software for your system instead of getting it from your distro 

lol.... I'm building it for the distro ;)

**Comment by pierrejoye** [comment]
Hehe yes Remi maintains fedora/rhel packages.

Remi, is the fix good for you?

**Comment by vapier** [comment]
the default generic x86 uses `-mfpmath=387` which is not exact/standards compliant.  if you want to support old processors (Pentium II and older), then you're just going to have to accept that the floating point code on those systems are inferior.  i don't think we should be trying to support floating point idiosyncrasies.

**Comment by remicollet** [comment]
Indeed (after a quick set of local build), -msse -mfpmath=sse fix the failed test.

**Comment by pierrejoye** [comment]
So the conclusion is that we do not add these flags.

Remain the skip test for x86 and document this option if one wants to achieve the same results.

Correct?

**Comment by vapier** [comment]
the fun thing is that each arch might have their own weirdness.  Alpha defaults to non-IEEE compliance (they use their native fp hardware too since it's faster, but it's been known to be off).  older ARM cpus (before neon standardized things) had a large number of diff floating point coprocs, but no great way of detecting in software or build time which was active.

we could update the README with info on some known test failures that occur when the floating point hardware is off a bit (rounding errors).  the runtime behavior of gd is probably not going to be noticed by people ... some pixels will get rounded up, some rounded down.  i think the delta image here shows that too -- i bet anyone looking at the original and the computed one can't tell the difference :).
