### ISSUE TITLE
GD and GD2 image formats are not documented

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#288]
Even though both formats are considered as being obsolete, their structure should be documented (if only for historic purposes). I've started documentation of the GD2 image format (mainly from reading the source code, and doing a few tests). This is what I have so far:

	* Structure of a GD2 image file:
	*  - file header
	*  - color header (either truecolor or palette)
	*  - chunks of image data (chunk-row-wise, top to bottom, left to right)
	*
	* All numbers are stored in big-endian format.
	*
	* File header structure:
	*  signature     - 4 bytes (always "gd2\0")
	*  version       - 1 word (e.g. "\0\002")
	*  width         - 1 word
	*  height        - 1 word
	*  chunk_size    - 1 word
	*  format        - 1 word
	*  x_chunk_count - 1 word
	*  y_chunk_count - 1 word
	*
	* Recognized formats:
	*  1 - raw palette image data
	*  2 - compressed palette image data
	*  3 - raw truecolor image data
	*  4 - compressed truecolor image data
	*
	* Truecolor image color header:
	*  truecolor   - 1 byte (always "\001")
	*  transparent - 1 dword (ARGB color)
	*
	* Palette image color header:
	*  truecolor   - 1 byte (always "\0")
	*  count       - 1 word (the number of used palette colors)
	*  transparent - 1 dword (ARGB color)
	*  palette     - 256 dwords (RGBA colors)
	*
	* Chunk structure:
	*  Sequential pixel data of a rectangular area (chunk_size x chunk_size),
	*  row-wise from top to bottom, left to right:
	*  - 1 byte per pixel for palette images
	*  - 1 dword (ARGB) per pixel for truecolor images
	*
	*  Depending on format, the chunk may be ZLIB compressed.

There seems to be a glitch (perhaps a one-off bug): writing an image with 256x256 pixels and the default chunk size of 128 outputs 3x3 chunks.

@kosinix I hope this is helpful. Please report back any mistakes or what could be improved.

**Comment by cmb69** [comment]
The GD doc was rather simple, so I've committed 5ee392d6.

**Comment by kosinix** [comment]
@cmb69,

This info is gold! One cant find anything on the web about the GD format. Thank you.

> There seems to be a glitch (perhaps a one-off bug): writing an image with 256x256 pixels and the default chunk size of 128 outputs 3x3 chunks.

Ha! I thought I was imagining things. Will keep you guys posted if I find anything. Thanks again.

**Comment by cmb69** [comment]
> This info is gold! One cant find anything on the web about the GD format.

Firstly, GD and GD2 are image formats invented by libgd, so we're the ones who have to document them. Secondly, I presume that nobody else implemented GD/GD2 support. GD is hardly more than a raw data format (without even RLE); GD2 might allow for better compression than RLE enabled formats (such as TGA and BMP), but it lacks any synchronization and integrity checks.

> Will keep you guys posted if I find anything.

Yes, please! :-)

BTW: for your purpose to export/import image data, you're most likely better off with `image(createfrom)gd()` than `image(createfrom)gd2()`. The former contains the image data in row-major without any chunking. That's quite close to your suggestion in #285. Using `pack()`/`unpack()` might even deliver rather good performance with PHP.

**Comment by cmb69** [comment]
> BTW: for your purpose to export/import image data, you're most likely better off with `image(createfrom)gd()` than `image(createfrom)gd2()`.

As I've [learned recently](http://news.php.net/php.cvs/94175), `imagegd()` doesn't work well for truecolor images (which get converted to palette using dithering). :disappointed:

**Comment by kosinix** [comment]
I used imagegd2 to export the pixels for truecolor images. To avoid chunking, set chunksize to the max image dimension (height or width whichever is bigger). There is 4096 limit (GD2_CHUNKSIZE_MAX) but most pics I'm working on does not go beyond 3k anyways. I also tried doing it with chunks, but its impossible to do some image processing operations with chunking ( a correct floyd-steinberg algorithm for example. Doing it with chunks would result in grid like patterns). I also store the exported pixels as binary string in memory and turns out it only consumes a minuscule amount of memory even for huge pictures, on a 512 Mb server. As oppose to storing it as an array which can easily ran memory out. However I encountered, more problem along the way, like with string concatenation of the processed result pixels. It relates to memory fragmentation which consumes a lot memory. I can solve it by using sprintf for string concatenation but then performance would suffer. Its like Im doing whack-a-mole with memory and performance.

I dropped the idea entirely. After testing the performance and fine tuning for a week, the performance gain is underwhelming in (php 5.6 and below). As matter of fact on php 7, imagecolorat is way faster than processing raw pixels. The only viable solution is a built in export pixels in C. But then that would leave old php versions out. So I'll just stick with imagecolorat for now and recommend PHP 7.

**Comment by cmb69** [comment]
@kosinix Interesting! php/php-src@0bf11d1e is supposed to speed up `imagecolorat()` and `imagesetpixel()` even more for PHP 7.2+.

> […] a correct floyd-steinberg algorithm […]

I haven't had a closer look at image dithering in libgd, but from this I presume that the results could be improved. I'll try to see to it.

**Comment by cmb69** [comment]
FTR: I've opened issue #293 some days ago.

**Comment by cmb69** [comment]
Okay, I guess this ticket can be closed now.
