### ISSUE TITLE
gdImageStringFT()'s brect out-of-bounds

### ISSUE THREAD

**Issue by cmb69** [libgd/libgd#301]
I've noticed that a [PHP test case](https://github.com/php/php-src/blob/PHP-7.0.11/ext/gd/tests/bug48732.phpt) fails when PHP has been compiled against an external libgd, but with the same libfreetype.

Consider the following slightly modified transscript of the test:

```
#include "gd.h"
#include "gdtest.h"


int main()
{
    gdImagePtr im;
    int black, red, green;
    char *fontpath = gdTestFilePath2("gdimagestringft", "Tuffy.ttf");
    int brect[8];
    FILE *fp;
    int i;

    im = gdImageCreate(150, 50);
    gdImageColorAllocate(im, 255, 255, 255);
    black = gdImageColorAllocate(im, 0, 0, 0);
    red = gdImageColorAllocate(im, 255, 0, 0);
    green = gdImageColorAllocate(im, 0, 128, 0);
    gdImageLine(im, 10,0, 10,49, green);
    gdImageStringFT(im, brect, black, fontpath, 12, 0, 10, 20, "ABCEDFGHIJKLMN\nopqrstu\n");
    gdImageRectangle(im, brect[6],brect[7], brect[2], brect[3], red);

    fp = fopen("bug00301.png", "wb");
    gdImagePng(im, fp);
    fclose(fp);

    for (i = 0; i < 8; i += 2) {
        printf("%d, %d\n", brect[i], brect[i+1]);
    }
    gdImageDestroy(im);
    gdFree(fontpath);

    return gdNumFailures();
}
```

This results in the following image:
![bug00301](https://cloud.githubusercontent.com/assets/2306138/18479714/4cfe06a8-79d6-11e6-8f56-8481386756ba.png)
The green line is drawn at the given x-coordinate for gdImageStringFT() (i.e. 10), the red rectangle is drawn at the resulting brect coordinates. One can see that the text indeed starts at x=10, but the bounding rectangle extends 2 pixels to the left, what looks wrong to me.

Also note that the test program outputs:

```
8, 41
140, 41
140, 6
8, 6
```

**Comment by cmb69** [comment]
For reference, this is what PHP's bundled libgd produces:
````
10, 47
137, 47
137, 8
10, 8
````
![bug48732](https://cloud.githubusercontent.com/assets/2306138/18483418/39010516-79e4-11e6-8ce5-458789949fcd.png)

**Comment by jsheares** [comment]
Has this issue been look at?  In my case, I am linking against an external libgd lib in a C program.  I get wrong brect coordinates depending on where the text is drawn.   

Below is a series images showing the letter W drawn at different Y positions with the brect border around them.  In all three, brect seems extend too far to the left and possibly to the right and to the bottom,  

I am going to talk about the top row next.  The first image shows what you would expect  brect to look like at the top row.  But, in the second image drawn at 6,20, brect is overlapping the top row. In third image drawn at 6,19, it seems to return to normal.

I want to be able to draw precisely placed text, but this issue is a show stopper at the moment

gdImageStringFT(img, brect, -65280, "Arial", 20, 0, 6, 21, "W");
![w_arial_p20_x6_y21](https://user-images.githubusercontent.com/17779715/29149909-0654b8dc-7d2c-11e7-8f7f-56c8f216c2ae.png)

gdImageStringFT(img, brect, -65280, "Arial", 20, 0, 6, 20, "W");
![w_arial_p20_x6_y20](https://user-images.githubusercontent.com/17779715/29149929-1ef25098-7d2c-11e7-9ca1-61bb8a06e3d9.png)

gdImageStringFT(img, brect, -65280, "Arial", 20, 0, 6, 19, "W");
![w_arial_p20_x6_y19](https://user-images.githubusercontent.com/17779715/29149932-24c66d6a-7d2c-11e7-9738-e6b3ee0253b4.png)

**Comment by cmb69** [comment]
At least part of the problem is that GD caters to rounding issues with some [suboptimal code](https://github.com/libgd/libgd/blob/8e7fca0057483d4225fc10d719daae08df88e456/src/gdft.c#L1584-L1588). The [solution in PHP's bundled libgd](https://github.com/php/php-src/blob/c8efaea1e3f93b5b836a38c6985b67983b1dc95a/ext/gd/libgd/gdft.c#L1205-L1213) appears to be better.
