### ISSUE TITLE
visual studio builds lack getopt

### ISSUE THREAD

**Issue by vshulga** [libgd/libgd#401]
See https://github.com/libgd/libgd/commit/2db153a93e22c9cd53022e131915c1000259eb52

**Comment by vapier** [comment]
we can probably just import a getopt implementation from like FreeBSD for VS builds

**Comment by cmb69** [comment]
Maybe https://gist.github.com/superwills/5815344 is an option.

**Comment by cmb69** [comment]
@vapier I've had a closer look at the getopt replacement, and the one mentioned above appears to work fine. However, MSVC doesn't know about `mkstemp()` so I've employed the following replacement:
````
#ifdef _MSC_VER
/* MSVC doesn't know mkstemp(), sigh ... */
#include <fcntl.h>
int mkstemp(char *template)
{
	int fd;

	do {
		if (!_mktemp(template)) {
			return -1;
		}
		fd = _open(template, _O_RDWR|_O_CREAT|_O_EXCL);
	} while (fd == -1 && errno == EEXIST);
	return fd;
}
#endif
````
This also works fine so far, but apparently ignores the "b" flag in the [fdopen()](https://github.com/libgd/libgd/blob/b7977b574dbbb1ba7d3e109e55ab08b7d76fb42a/src/webpng.c#L275) call, so everytime an image is modified by webpng (`-i` or `-t`) it gets corrupted. Any ideas on how to work around this? Is it even necessary to write to a temporary file in the first place – can't we simply write to `infile` instead? Since `gdImagePng()` doesn't report success/failure, it doesn't seem to make a real difference.

**Comment by vshulga** [comment]
maybe std::tmpfile()?

**Comment by vapier** [comment]
hopefully master should be fixed now for windows builds.  if you're still seeing getopt problems, let us know.  if you're seeing other portability problems (unrelated to getopt), please file a new issue.
