### ISSUE TITLE
src/Makefile.am: add snprintf.c to EXTRA_DIST

### ISSUE THREAD

**Issue by vshulga** [libgd/libgd#416]
I am trying to compile libgd using VS 2010 and the build is failing: snprintf.c mentioned in CMakeLists.txt is missing

**Comment by cmb69** [comment]
Visual Studio [supports `snprintf()` only as of VS 2015](https://stackoverflow.com/questions/2915672/snprintf-and-visual-studio-2010#8712996). I don't think we should add a fallback for older versions.

**Comment by vapier** [comment]
our cmake build does a version check and includes it only when the windows toolchain is old.  i've fixed it since we already include the file in the git repo and build system, and it's easier for the release branch.

```
if(MSVC AND MSVC_VERSION LESS 1900)
    set(LIBGD_SRC_FILES ${LIBGD_SRC_FILES}
        snprintf.c
    )
endif(MSVC AND MSVC_VERSION LESS 1900)
```

if we want to drop support for those older versions, we can do it from everywhere.  but i'm too lazy for that ;).
