### ISSUE TITLE
Potential infinite loop in gdImageCreateFromGif

### ISSUE THREAD

**Issue by velemas** [libgd/libgd#420]
The issue is fixed in PHP https://bugs.php.net/bug.php?id=75571 (patch https://bugs.php.net/patch-display.php?bug_id=75571&patch=fix-75571&revision=latest) and this may be related to https://github.com/libgd/libgd/issues/158

**Comment by cmb69** [comment]
Thanks. I've already send a patch via <b669d573-a217-b357-3b61-dcc7714da40e@libgd.org> a while ago. However, I'm not able to release a new version, since [`makedistcheck`](https://github.com/libgd/libgd/issues/407#issuecomment-325981454) fails on my Vagrant box due to permission issues (a temporary `aclocal.m4` is supposed to be deleted, but the perms are `0444`).

And yes, #158 will also be fixed by the patch.

**Comment by cmb69** [comment]
[CVE-2018-5711](http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-5711) has been assigned.

**Comment by totemofwolf** [comment]
what is the major difference bettween 
phpsrc/ext/gd/libgd and this repo [https://github.com/libgd/libgd](url)

**Comment by vapier** [comment]
this is the upstream project
