### ISSUE TITLE
gdImageCrop neglecting transparency?

### ISSUE THREAD

**Issue by y-a-v-a** [libgd/libgd#432]
Hi,
I'm the maintainer of node-gd, the NodeJS bindings to libgd. Someone came with the following issue in the node-gd repository, and after some research in libgd, I think it is a bug in libgd. In short: trying to crop a source image with transparency results in a cropped destination image with all black for where the source image was transparent.

According to https://github.com/libgd/libgd/blob/master/src/gd_crop.c#L53  gdImageCreateTrueColor is being called which, as stated here https://github.com/libgd/libgd/blob/master/src/gd.c#L264 will always be filled with black by default. 

So the destination image of gdImageCrop is filled with black by default. When gdImageCopy is called to crop the source onto the destination, it nicely blends the source color onto the destination since, quote: "alpha blending is now on by default". As per https://github.com/libgd/libgd/blob/master/src/gd.c#L341. And programatically you're unable to modify the destination (i.e. cropped image) before the source is copied upon it.

So the solution would be, as far as my knowledge of C goes, which is effectively very little, to be honest, to set the alphaBlendingFlag of the destination image for gdImageCrop to `0` before copying the source to it.

Issue in node-gd repo: https://github.com/y-a-v-a/node-gd/issues/60

Cheers,
Vincent

**Comment by cmb69** [comment]
Thanks for reporting this issue, and coming up with a solution! The only question that remains is whether we should reset the alphaBlendingFlag (BTW, a misnomer since it actually stores a [gdEffect*](http://libgd.github.io/manuals/2.2.5/files/gd-h.html#Effects)) after `gdImageCopy()`, or not. Probably we should.

**Comment by cmb69** [comment]
Interesting, PHP's bundled libgd doesn't seem to be affected by this issue, because the implementation was "slightly" different from the start: [libgd](https://github.com/libgd/libgd/commit/f67452e1f82f1c2496e0859d638172bee74b43a0#diff-79c20e3f9e3b6d2154f9af284d0ce360) vs. [PHP](https://github.com/php/php-src/commit/a991360344ed5bca7c20f74a10891d0fc52f0c9f#diff-baf46fc7ef24ab65d0c007d1ed48a483). 

@pierrejoye Is there any particular reason why the implementations differ so much? Which implementation would be preferable?
