### ISSUE TITLE
Will libgd license affect by GPLv3 when libimagequant is enbale?

### ISSUE THREAD

**Issue by willson-chen** [libgd/libgd#630]
Here is the [homepage](https://pngquant.org/lib/) of libimagequant.

Quate from the description of `License`
> For Free/Libre Open Source Software it's available under GPL v3 or later with additional copyright notices for older parts of the code.

libimagequant's license is **GPLv3**.

**Comment by willson-chen** [comment]
@pierrejoye @cmb69 @vapier

**Comment by cmb69** [comment]
Ugh, IANAL, but I think linking against a GPLv3 library would a license violation.

Maybe @kornelski can clarify?

**Comment by vapier** [comment]
> linking against a GPLv3 library would a license violation.

it should not be.  the license of GD is BSD/MIT-like which has no problem being merged into a GPL project.

it is the user's responsibility to understand the license of the final combined project.  if they choose to use GPL or similar projects, then they need to account for it.

**Comment by vapier** [comment]
to be clear, everyone already has to do this for every single project in the world, not just gd, even if they don't realize it.  toolchains, compilers, C libraries, and build systems all have their own licenses that need to be taken into consideration as to their impact on the final objects.  in the FOSS world, glibc & gcc & autotools & make & cmake have reasonable licenses where producing shared libs/programs don't have "viral" licenses.  but if you statically linked them, the final programs would be subject to the LGPL.

every 3rd party lib gd uses is in the same boat: users need to evaluate the impacts they have on their final project before using them.  linking against a GPL library means the final linked outputs are subject to the GPL, but it doesn't mean the gd source code itself is suddenly GPL.

gd has no requirement on specific projects so it's up to the user to select the right one for their needs.  we write to APIs (e.g. POSIX) and the user picks an environment/dependency that satisfies those APIs, which means they also pick the licensing requirements.

so i don't think anything needs to be done on our side.  this is simply how licensing works.

**Comment by kornelski** [comment]
Yes, it affects the license. My understanding is that it's fine to link with it, but the resulting product would be GPL, and products using libgd with libimagequant would be GPL too.

**Comment by willson-chen** [comment]
Hi all,

Considering the number of gd dependencies, do you think it is a good idea to list all the depencies and their license? So that gd users can choose proper features and avoid legal risks. We could add the list to `README.md`, `COPYING` or a new file named `Licensing.md`.

I think this is [a good example](https://github.com/DoubangoTelecom/doubango/blob/master/Licensing.md).

**Comment by vapier** [comment]
it absolutely must not be added to COPYING.  the point of that file is only to list gd's license.

the reason doubango has that document is because they're bundling 3rd party libraries directly in their distribution which means they have a legal obligation to provide summaries of some sort.

i'm not completely against providing a short list of (package, version, license) ourselves, but the audience here seems kind of limited: we're aren't talking about distro/webserver users (since the distro handles that for them), we're really only talking about building & embedding gd directly into their own product/device, and providing a summary on gd's side does not relieve them of any legal obligations.  they still must go through every library/package they install/include in their product and make sure that they are complying with all the license requirements.  at that time, they should be figuring out what is or is not acceptable to their product which includes seeing whether they want to include GPL projects.  if they're anti-GPL because they're lazy, then they aren't going to use the Linux kernel, which means we're talking an even smaller subset of users of this information.

**Comment by willson-chen** [comment]
Fair enough. So we do not need to do anything about this issue, right?

**Comment by pierrejoye** [comment]
Actually it may be an issue. And I did not know they change to GPLv3, last time I checked (when we have the PR for it), it was not the case if I am not mistaken.

The main reason is the following:

- We link statically libimagequant 
- Consequently someone using LibGD will link directly as well to libimagequant 

So we must mention it in the README, INSTALL and License. As it may causes issues for the user. @vapier 

It also means that we may drop support for libimagequant sooner, or move to shared lib usage (then it is like libc or the kernel.

**Comment by vapier** [comment]
if you're referring to the `LIQ_BUILD` logic that's only in cmake, then that needs to be deleted entirely.  we shouldn't be providing package management logic for people.

**Comment by willson-chen** [comment]
> It also means that we may drop support for libimagequant sooner, or move to shared lib usage (then it is like libc or the kernel.

AFAIK, libimagequant affects libgd's license no matter link statically or dynamically. So dropping support for libimagequant is the only way.

**Comment by vapier** [comment]
to clarify, nothing affects libgd's license.  our license for our code is clear: it's in the COPYING file.  there is no qualification on that statement.
NB: when i say "BSD" below, i'm referring to our COPYING file, even though it strictly isn't a BSD license.  it just makes things easier for discussion purposes.

the use of 3rd party libraries still does not affect the license of libgd's source, it only might affect the combined work (i.e. the compiled outputs).  and at that point, it's up to the user to determine what is appropriate for their project/use case, not us.

linking BSD projects & GPL projects is fine.  it just means the *combined work* (aka compiled objects) are subject to the GPL licensing requirements.  it does *not* mean the BSD projects are now GPL projects and that the libgd source can no longer be licensed under the BSD.

imo we should be dropping the logic that downloads & builds LIQ, not because of any licensing concerns, but because it's fundamentally wrong/inappropriate for gd to be doing this in the first place.  gd is a library, it is not a distribution/packaging service.  if users want to utilize LIQ, then they need to download+build+install it themselves.  it's not like we're doing this for any of the other 3rd party libs we support (zlib/libpng/libjpeg/etc...).

but that is orthogonal to whether we optionally support the LIQ library.  there might be a technical reason for dropping that, but it certainly isn't a licensing reason.

**Comment by willson-chen** [comment]
> imo we should be dropping the logic that downloads & builds LIQ

Hi, @vapier. We have dropped it in PR #534. Could you please offer some suggestions about what we shall do next?

**Comment by vapier** [comment]
hmm, i thought i synced my local checkout first, but yeah looks like it's gone.  i don't think we bundle any other packages, so i don't think we need to do anything.  i'm generally not keen on trying to provide advice to users lest they get the false impression that they were covered by something we said, and lists like doubango's is certainly nice looking, but it's just one more thing we need to manually maintain wrt external projects that are free to change behavior over time.

if there are labels we could apply to the source for something like SPDX to consume to declare the relationships, i'd be for that, and that should address concerns about tracking things.  but i think that relational information would be expressed at a higher level than us (i.e. a distro's packaging system).

**Comment by willson-chen** [comment]
What about reminding gd users of the GPL license of libimagequant in `README`, `doc/INSTALL` and License as @pierrejoye said? GD depens on libimagequant directly after all, which make me feel obligated to remind the gd users.
