### ISSUE TITLE
Which version of PHP will support AVIF?

### ISSUE THREAD

**Issue by gbiorczyk** [libgd/libgd#684]
Hey,

I am very pleased that the AVIF support has been successfully implemented. Thank you very much!

Do you know which version of PHP will support this version of the GD library? Im the time it takes to implement this?

**Comment by vapier** [comment]
prob want to ask the php folks like @remicollet as most of us don't have any interaction with php

**Comment by cmb69** [comment]
Pretty sure it will be PHP 8.1.0, at the earliest. There is already a [feature request](https://bugs.php.net/bug.php?id=80828) which you can track.

**Comment by gbiorczyk** [comment]
I would be very grateful for your help @remicollet. I am the author of [a plugin for WordPress](https://wordpress.org/plugins/webp-converter-for-media/) and I am looking forward to the possibility of AVIF support.

**Comment by cmb69** [comment]
I've already chatted about AVIF/HEIF support with Martin (who made the feature request), and he said he's going to try to work on that (it's not that simple, because PHP's bundled libgd need to be updated first, and there need to be libheif and libavif packages for Windows).

**Comment by vapier** [comment]
excellent, thanks for the links @cmb69

**Comment by gbiorczyk** [comment]
@cmb69 Is there any time frame for the possibility of implementing this in PHP?

**Comment by cmb69** [comment]
New features are going into the next version (PHP 8.1), if somebody actually implements it.

**Comment by morsssss** [comment]
PHP 8.1 should be released in November - so, if all goes well with support, you could see it then!

@cmb69 , we should coordinate efforts here. There's [this PHP feature request](https://bugs.php.net/bug.php?id=78832) as well!

**Comment by cmb69** [comment]
@morsssss, that feature request has already been closed. Better refer to https://bugs.php.net/bug.php?id=80828. And PHP can use system libgd or bundled, but the latter is usually used on Windows only.

Anyhow, all this shouldn't be discussed in this repo, since it is not related to PHP. It's like discussing details about libgd on the Linux kernel ML. :)

**Comment by morsssss** [comment]
sg :)

**Comment by remicollet** [comment]
BTW, please notice that libheif have pattern issue and is excluded from various distributions because of this

So, these distributions (e.g. RHEL, CentOS, Fedora...) won't have the feature enabled (in libgd or in PHP)

and libgd don't have support for dynamic loading codecs (like IM have, and like vips will have soon)

**Comment by cmb69** [comment]
> BTW, please notice that libheif have pattern issue and is excluded from various distributions because of this

You mean "patent issues", right? If so, that would be bad.

**Comment by remicollet** [comment]
> > BTW, please notice that libheif have pattern issue and is excluded from various distributions because of this
> 
> You mean "patent issues", right? If so, that would be bad.

Yes patent encumbered

**Comment by goashir** [comment]
and what happen in 2024?
is any plan to add avif to php?

**Comment by cmb69** [comment]
See https://www.php.net/manual/en/migration81.new-features.php#migration81.new-features.gd. Available as of PHP 8.1.
