### ISSUE TITLE
Installation of gd extension in Apache Netbeans 12.6 for Windows 11 (using xampp for apache netbeans)

### ISSUE THREAD

**Issue by roslyk** [libgd/libgd#827]
Hello Folks!

_I am not sure this is the right place for this question. If not, feel free to refer me to somewhere else._

I am quite new at PHP-development. 

I was hoping to use the function imagettfbbox() in my php project.  This function is in the gd extension. 

To install the gd extension I follow the guide here: https://codeanddeploy.com/blog/php/how-to-install-php-gd-extension-on-windows-wamp-and-xampp-server.

The guide says to "kindly download" the file php_gd2.dll by using the website https://libgd.github.io/pages/downloads.html. I go to the website https://libgd.github.io/pages/downloads.html. I click on the link "libgd project". This leads me to your page:  https://github.com/libgd/libgd/releases.

My question is then: How do I download the file "php_gd2.dll" from your page (https://github.com/libgd/libgd/releases)?

Any help is appreciated!

Kind regards, Christian

**Comment by vapier** [comment]
sorry, we don't provide plugins for php.  i don't think we ever have.  not sure why the guide is telling you that.

i would expect wherever you got your php install would provide/include gd as a plugin instead.

maybe @pierrejoye has some tips or better guidance.

**Comment by cmb69** [comment]
Well, actually this is the wrong place; you're better off asking these kinds of questions on StackOverflow or some other PHP support channel.

That said, php_gd2.dll is bundled with any PHP on Windows binary, and likely already contained in your ext/ folder. Otherwise you can download the suitable zip from https://windows.php.net/downloads/releases/ and take the DLL from there. See also https://www.php.net/manual/en/image.installation.php.
