### ISSUE TITLE
Binary Backup compatibility comment in gdImageStruct

### ISSUE THREAD

**Issue by Jeevhi** [libgd/libgd#844]
Hi,

I noticed following comment in the `gdImageStruct` and wondering (and worried) about `binary backwards compatibility`. Is this structure saved/loaded somewhere directly that `alpha` was moved later to for `binary backwards compatibility`

```
 /* These are valid in palette images only. See also
           'alpha', which appears later in the structure to
           preserve binary backwards compatibility */
```

Thanks

**Comment by vapier** [comment]
gd aims to provide ABI compatibility following normal library rules.  all releases since gd-2.1.0 have used the same ABI name.

please use the [Discussions](https://github.com/libgd/libgd/discussions) for questions like this in the future.

**Comment by Jeevhi** [comment]
ok, however it is recommended to make this structure opaque to avoid such issues. 

Just a feedback.

**Comment by vapier** [comment]
making it opaque is an ABI break.

if it were opaque, we'd have to provide accessor functions for every field we want to expose to the user, and those formats have to stay stable. so it's trading one pain point for another.

this struct is meant to expose fields. there are others which are opaque because there isn't anything for the user to access.

there is more to ABI than just struct layout.
